name: Build

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Build
        run: yarn build
      - name: Lint (Linux only)
        run: yarn lint
        if: matrix.os == 'ubuntu-latest'
